data:
  cafa5: "cafa5"
  train: "cafa5/train"
  test: "cafa5/test"

plot:
  out: "output/plot"

cluster:
  out: "clusters"
  train:
    sequence: "cafa5/train/train_sequences.fasta"
    threads: 12
    max_seq_len: 2048
    coverage: 0.8
    min_seq_id: 0.3
    cluster_mode: 0
    cov_mode: 0
    reassign: true
  test:
    sequence: "cafa5/test/testsuperset.fasta"
    threads: 12
    max_seq_len: 2048
    coverage: 0.8
    min_seq_id: 0.3
    cluster_mode: 0
    cov_mode: 0
    reassign: true

metadata:
  data_folder: "cafa5/train"
  cluster_folder: "clusters"
  translated_with_aspect: False
  out: "output"

dataset:
  protein: "cafa5/train/train_sequences.fasta"
  metadata: "output/metadata.tsv"
  go_sentence: "output/go_sentences.tsv"
  go-basic: "cafa5/train/go-basic.obo"
  type: "ProteinReducedGOConcatenatedDataset"
  seed: 42
  test_size: 0.1
  out: "datasets/protein_reduced_go_concatenated"

embed_seq:
  device: "cuda"
  model: "Rostlab/prot_t5_xl_half_uniref50-enc"
  max_seq_len: 2048
  emb_type: "per_prot"
  uniprot: "embeddings/per-protein.h5"
  url: "https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/embeddings/uniprot_sprot/per-protein.h5"
  output: "embeddings/sequence_embeddings.h5"
  train_set:
    sequence: "cafa5/train/train_sequences.fasta"
  test_set:
    sequence: "cafa5/test/testsuperset.fasta"

embed_text:
  source: "output/metadata_concatenated.tsv"
  model: "microsoft/Phi-3.5-mini-instruct"
  tokenizer: "microsoft/Phi-3.5-mini-instruct"
  sentence_level: "sentence_embeddings"
  max_len: 2048
  device: "mps"
  output: "embeddings/concatenated_text_embedding.h5"

embed_vis:
  subsample: 1000
  seed: 42
  n_neighbors: 15
  min_dist: 0.1
  n_components: 2
  metric: "cosine"
  metadata: "output/metadata.tsv"
  GO: "output/go_sentences.tsv"
  text_embeddings: "embeddings/text_embeddings.h5"
  sequence_embeddings: "embeddings/sequence_embeddings.h5"

train:
  dataset: "datasets/protein_reduced_go_concatenated"
  prot_emb_file: "embeddings/sequence_embeddings.h5"
  text_emb_file: "embeddings/text_embeddings.h5"
  go_sentence: "output/go_sentences.tsv"
  num_workers: 1
  seed: 42
  val_size: 0.1
  project: "protein-clip"
  run_name: "CLIPLoss-ReducedGOConcatenated"
  prot_embed_dim: 1024
  text_embed_dim: 3072
  projected_dim: 1024
  intermediate_dim: 2048
  num_hidden: 3
  dropout: 0.1
  activation: "GELU"
  loss: "CLIPLoss"
  loss_params:
    temperature: 0.07
  accelerator: "gpu"
  precision: "32-true"
  batch_size: 128
  lr: 0.0005
  max_epochs: 16
  gradient_clip_val: 1.0
  logit_scale_required: True
  padding: False
  early_stop: True
  out: "embeddings/output_embeddings.npz"
  umap_params:
    n_neighbors: 100
    min_dist: 0.0
    metric: "euclidean"
    n_components: 2
