# params.yaml
data:
  cafa5: "cafa5"

cluster:
  outs: "clusters"
  train:
    threads: 12
    coverage: 0.8
    min_seq_id: 0.3
    cluster_mode: 0
    cov_mode: 0
    reassign: true
  test:
    threads: 12
    coverage: 0.9
    min_seq_id: 0.5
    cluster_mode: 0
    cov_mode: 0
    reassign: false
embed:
  device: "cuda"
  outs: "embeddings"
  model: "Rostlab/prot_t5_xl_half_uniref50-enc"
  max_seq_len: 1024
  emb_type: "per_prot"
  train_set:
    sequences: "cafa5/train/train_sequences.fasta"
    outputs: "embeddings/train_embeddings.h5"
  test_set:
    sequences: "cafa5/test/testsuperset.fasta"
    outputs: "embeddings/test_embeddings.h5"
  dataset:
